### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by juanmijm** [sfstar/hass-victron#107]
I can't configure the integration, when I click on add integration I get this message:

![error_victron](https://github.com/sfstar/hass-victron/assets/62819001/541bf821-d814-41dd-8077-2c983541a953)

I have installed version 0.1.2 from hacs and I have home assistant in the latest version, 2023.8.1

any solution? thank you!

**Comment by cybertza** [comment]
full reboot HASS

**Comment by juanmijm** [comment]
> full reboot HASS

I have restarted HASS and the server several times, and it still doesn't work

**Comment by juanmijm** [comment]
> full reboot HASS

Today I have seen the new update of the integration, excited I have updated, restarted the server, and I have been disappointed again to verify that the same error continues... :(

**Comment by cybertza** [comment]
No problem on my side ?RegardsOn 24 Aug 2023, at 14:08, juanmijm ***@***.***> wrote:﻿

full reboot HASS

Today I have seen the new update of the integration, excited I have updated, restarted the server, and I have been disappointed again to verify that the same error continues... :(

**Comment by juanmijm** [comment]
I don't know where the problem is, but this is the only thing that doesn't work in my Home Assistant and I'm annoyed.

If I configure the modbus connection directly in yaml code it works for me, but it's cumbersome and I'd like to use your integration.

**Comment by juanmijm** [comment]
![image](https://github.com/sfstar/hass-victron/assets/62819001/e5673b54-e67d-42b2-b988-4e9da22f76b8)

**Comment by cybertza** [comment]
https://github.com/home-assistant/core/issues/65785

so looking at some other posts it seems that one of your other integrations could be causing the issues, there seems to be hints at how to trouble shoot this, its doesnt seem to be related to this plugin but infact a plugin and therefor home assistant related.

Analizing the logs like they have perhaps give us insight, i assume it would be with pymodbus or something, but its hard to guess, as im not sure what all gets loaded with this plugin.

**Comment by juanmijm** [comment]
I have another Ingeteam brand inverter, also configured by modbus with another HACS integration, surely it could be due to that? so I can't have two integrations that use modbus at the same time?

**Comment by juanmijm** [comment]
https://github.com/vortizhe/home-assistant-ingeteam-modbus

This is the another integration, thanks!

**Comment by sfstar** [comment]
Based on a quick look at the provided link I saw that pymodbus version 2 was still used by that integration.
Which is no longer compatible with this integration and the ha core mdobus (yaml) integration. (both are using a >v3.1.0 release for quite some time now). 
If you want this integration to work it is best to either disable the integration that is using the older pymodbus version or to get them to update to the v3 library version since it's also not ensured that the yaml modbus integration remains working with a <v3.3.1. library version

**Comment by juanmijm** [comment]
Thank you very much, I will tell the creator of the other integration

**Comment by juanmijm** [comment]
I forgot to close the issue, thanks again!
