### ISSUE TITLE
Cannot connect 2 gx devices

### ISSUE THREAD

**Issue by AnjaHtl** [sfstar/hass-victron#108]
I was able to connect my first GX devices wich has  an one phase system. When I want to connect my second GX device, whch has a three phase system, I get the error "Only one instance of the victron integration supported at this time". How can I connect both devices?

**Comment by sfstar** [comment]
Hello @AnjaHtl,

Thank you for opening this feature request.
Multi sites aren't currently supported.
The implementation of this feature will be tracked in #162 .
Therefore closing this issue for now.
