### ISSUE TITLE
Dynamic ESS

### ISSUE THREAD

**Issue by andzie82** [sfstar/hass-victron#118]
Possible to implement the new feature Dynamic ESS?
![IMG_7389](https://github.com/sfstar/hass-victron/assets/48380052/b2fb0f4a-0d22-4ee6-8579-9f89f3964c61)
![IMG_7388](https://github.com/sfstar/hass-victron/assets/48380052/0f3c2b78-b359-4d7e-ab42-b0a5a9caab07)

**Comment by steve0564** [comment]
Where can I find further information about this feature?

**Comment by sfstar** [comment]
Unfortunately I cannot implement what victron doesn't expose via the modbus server.
You could open an issue here: https://github.com/victronenergy/dbus_modbustcp/issues to request that they expose this information via an modbus register.
Until then I'm closing this issue as wontfix as the solution lies outside the scope of the integration (for now)
