### ISSUE TITLE
Cerbo 3.0 Update in Read Me

### ISSUE THREAD

**Issue by Raini20** [sfstar/hass-victron#127]
The read me doesn't mention anything new regarding the Cerbo 3.0 Update.
I wonder if there are any incompatibilities after making the update.

@sfstar mentioned to update (but forgot because nothing major happened?):
https://github.com/sfstar/hass-victron/issues/82#issuecomment-1586135681

**Comment by OlePZ9** [comment]
Cerbo 3.0 ist working fine with the integration
