### ISSUE TITLE
More than one GX device not supportet

### ISSUE THREAD

**Issue by GerhardLang** [sfstar/hass-victron#131]
Hello.

I do have a configuration with more than one GX devices which I want to have in Home Assistant.
It would be great if the Integration would support multiple  instances.
Actually I need to create all modbus sensors  needed by hand. What a pity because the Integration is great.

**Comment by pos-ei-don** [comment]
+1.
I also have 2 Systems, a 48V and a 24V System.

**Comment by gris74** [comment]
+1 also have more than 1 system

**Comment by cyon30** [comment]
any work around on this?

**Comment by GerhardLang** [comment]
Hi, just my workaround:
I did create the modbus entries for the relevant values of each GX device, so I do not have such an amount of unnecessary values and I solved my problem with more devices.

**Comment by cyon30** [comment]
I have 5 sites here at the main office and want some values at the main screen here at the ofiice

**Comment by sfstar** [comment]
Further tracking of this feature request will be done in #162.
Please let your voice be heard over there.
