### ISSUE TITLE
Victron value stops updating on UI, keeps getting value

### ISSUE THREAD

**Issue by sanchosk** [sfstar/hass-victron#139]
Not sure what happened, but for last few hours, my HA keeps displaying the value for my battery on the same level.
However, when I click on the details, it correctly shows the graph with the data, including the current value.
![image](https://github.com/sfstar/hass-victron/assets/2346083/ad7c71cc-9ef0-4c68-ae8a-35007718bcfc)

As one can see on the picture, the current state of battery is reported as 10%, however the HA displays last update 6 hours ago and reports 18%.

I did not do any update of HA or Victron that I am aware of.
Any idea what could be the reason this is happening?

**Comment by sfstar** [comment]
Thank you for opening this issue,

Could you perhaps check the logs of the HA instance to see whether there are any warnings or errors present at the time the integration stops reporting the entities values?

**Comment by sfstar** [comment]
Thank you for your reply and providing the debug logging.
I believe that the latest release v0.3.0 could also adress your issues since there were several stability improvements made between when this issue was reported and the latest release (released today).
Could you tell me if the issue is still occurring?

**Comment by sanchosk** [comment]
Unfortunately, it behaves the same.
Installed 0.3.0, it required restart of HA and after restart I, again, have this:



On May 19, 2024 11:18:34 AM GMT+02:00, sfstar ***@***.***> wrote:
>Thank you for your reply and providing the debug logging.
>I believe that the latest release v0.3.0 could also adress your issues since there were several stability improvements made between when this issue was reported and the latest release (released today).
>Could you tell me if the issue is still occurring?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sfstar/hass-victron/issues/139#issuecomment-2119165460
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/ Mail.

**Comment by sanchosk** [comment]
Unfortunately, even after 0.3.0 update, it did not work.
What I did:
Update to 0.3.0
Restart HA
Wait 2 minutes
Check the MPPT
It was unavailable.
Rescan, again, did the trick and the data is back...
![Screenshot_20240519-135425_Home_Assistant](https://github.com/sfstar/hass-victron/assets/2346083/48c97cfe-1761-49dc-b8db-fab9419aa989)

**Comment by sanchosk** [comment]
Update - with the latest HA update, the restart now works OK - after reboot I have again the victron MPPT back.
Thanks!
Closing the issue.
