### ISSUE TITLE
Added GX hub, but no entities available.

### ISSUE THREAD

**Issue by valentinjalba** [sfstar/hass-victron#141]
I made sure the IP address is correct and used the default port 502. I collected the GX's IP address from the VRM app. 

I have a Cerbo GX firmware v3.12.

**Comment by braamvh** [comment]
Have you enabled Modbus TCP on the Cerbo? Can you actually reach the Cerbo from Home Assistant?

**Comment by valentinjalba** [comment]
> Have you enabled Modbus TCP on the Cerbo? Can you actually reach the Cerbo from Home Assistant?

Thank you, this was exactly my issue. I did not realise I needed to enable something on the Victron side as well. Did some reading on where to enable Modbus TCP, enabled it and everything works like a charm.

**Comment by sfstar** [comment]
Closing issue as fixed by user
