### ISSUE TITLE
integration crashes my HA core

### ISSUE THREAD

**Issue by alwintichelaar** [sfstar/hass-victron#148]
when i wan't to connect the integration to my victon ip adress the HA core crashes.

**Comment by JBsDk** [comment]
Same
I have the problem since 2 Years now, check it out every few months but it stoll dosnt work.
no idea why.

**Comment by sfstar** [comment]
Hello,

Thank you for opening and responding on this issue.
Could you perhaps inform me of the Ha core version and integration version you are running?
Furthermore, do you have access to the HA core container logs?
If so, what error do you see (if any) before HA core crashes?

**Comment by sfstar** [comment]
Closing issue as stale (in an effort to cleanup the issue tracker).
Feel free to re-open if the issues persist
