### ISSUE TITLE
Missing solarcharger

### ISSUE THREAD

**Issue by usekevin1988** [sfstar/hass-victron#157]
Hello everyone.

maybe someone has a idea.

My system:

1x Multiplus II 48/5000 
3x SmartSolar MPPT 100/20-48V 
1x Cerbo GX
1x Pylontech US5000
1x EM24 Ethernet

I cant find my third SmartSolar in HA.

I did a rescan, but nothing has changed.
![grafik](https://github.com/sfstar/hass-victron/assets/114338301/fd570281-e10a-47c6-920b-5010944a9107)
![grafik](https://github.com/sfstar/hass-victron/assets/114338301/d3778b7e-25dc-4431-92f7-73c5b5de402b)

any idea, what im doing wrong? Theyre all on the same way connected to my CerboGX

**Comment by OlePZ9** [comment]
Sometimes the integration does not recognize MPPTs correctly , especially address 0/100. maybe there is something similar to higher addresses like 100.
You can include new sensors by using the Modbus integration by entering yaml code into configuration.yaml
![image](https://github.com/sfstar/hass-victron/assets/60582161/04dc39e9-4750-4ba7-ac16-af64506ef6da)

**Comment by OlePZ9** [comment]
![image](https://github.com/sfstar/hass-victron/assets/60582161/c379734f-962d-43c0-beba-3cf0ee974f28)
This has to be entered before the other, take the ip address from your Cerbo GX

**Comment by OlePZ9** [comment]
Use the mapping address for 280 instead of the number from my Codename take 215 instead of 226 for your third device

https://www.victronenergy.com/upload/documents/CCGX-Modbus-TCP-register-list-3.10.xlsx

![image](https://github.com/sfstar/hass-victron/assets/60582161/d6b6246b-db1b-47a2-ae6d-0661a44a343a)

**Comment by OlePZ9** [comment]
Luckily the integration accepts manual Modbus sensors beside its own ones

**Comment by sfstar** [comment]
Hello @usekevin1988,

Could you try the version on the main branch of this integration?
It contains the new unit id's and should allow for the solarcharger to be detected upon a rescan.

**Comment by sfstar** [comment]
The release (v0.2.0) has been shipped.
Closing issue, feel free to re-open if the issue persists with the new release
