### ISSUE TITLE
Power total and max capacity 

### ISSUE THREAD

**Issue by EckeFL** [sfstar/hass-victron#159]
The values for "Power max capacity" and "Power total" are to large by a factor of 1000.

Venus OS 3.11

![IMG_20240127_101735](https://github.com/sfstar/hass-victron/assets/50829150/6b1cd3db-7598-4bfa-9f8e-8ac84d6760c3)

**Comment by sfstar** [comment]
Hello @EckeFL,

Thank you for opening this issue.
I've escalated my support request (that I opened last year may) with victron to get clarification on whether the documentation is leading and the victron modbus server needs to be patched or the software is leading and we can patch this on our end.
This will be picked up once victron replies.

**Comment by sfstar** [comment]
Change will be included in next release
