### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by OlePZ9** [sfstar/hass-victron#16]
I am trying to install it on a backup system. the original Modbus integration had been disabled. I was able to install, but unable to configure the integration. I am using a 3 phase MPII 5000/48, cerbo GC, Pylontech LiFePO4 battery, 2x Fronius inverter (Symo 3 Phase), 1x MPPT 450/100, 1x MPPT 250/60. The Yaml integration had been disabled. Any idea?
![image](https://user-images.githubusercontent.com/60582161/209399189-27d7db55-9035-4d6e-a4a1-c270b529f238.png)

**Comment by OlePZ9** [comment]
![image](https://user-images.githubusercontent.com/60582161/209399647-43bd8d82-ca22-4717-a332-e39d87287d0d.png)

**Comment by Raini20** [comment]
Is your Modbus/TCP under "Settings -> Services" enabled and further under " -> Modbus/TCP -> Available Services" are your devices in the list?

**Comment by OlePZ9** [comment]
In another instance of HA my modbus connection is workin flawlessly. This is a test of the integration after removing all Modbus stuff from yaml

**Comment by OlePZ9** [comment]
Maybe I need to shutdown the other instance...

**Comment by OlePZ9** [comment]
I think, I got it: enter http:// before the IP address :-)
