### ISSUE TITLE
FREQUENCY_HERTZ was used from victron,

### ISSUE THREAD

**Issue by AnKloss** [sfstar/hass-victron#164]
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 2:01:49 PM (17 occurrences)
Last logged: 2:02:09 PM

FREQUENCY_HERTZ was used from victron, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfFrequency.HERTZ instead, please create a bug report at https://github.com/sfstar/hass-victron/issues
TIME_SECONDS was used from victron, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.SECONDS instead, please create a bug report at https://github.com/sfstar/hass-victron/issues
IRRADIATION_WATTS_PER_SQUARE_METER was used from victron, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfIrradiance.WATTS_PER_SQUARE_METER instead, please create a bug report at https://github.com/sfstar/hass-victron/issues
ENERGY_KILO_WATT_HOUR was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues

**Comment by sfstar** [comment]
Hello @AnKloss,

Thank you for opening this issue.
It should be fixed in release v0.1.6 thanks to the PR made by @ChristophCaina.
Therefore, closing this issue.
Feel free to re-open the issue if the warnings persist after upgrading to v0.1.6
