### ISSUE TITLE
First Feedback and idea for improvement

### ISSUE THREAD

**Issue by OlePZ9** [sfstar/hass-victron#17]
3 Phase is working well. My first proposal for improvement wuld be to add a unique ID (could be the same as entity, this would help to add them into dashboards. Additionally, the ability to add all (or more than one a a time) entity to a dashboard would help
![image](https://user-images.githubusercontent.com/60582161/209435456-ffe2c68e-6e2a-47c4-b72d-9f564c03c164.png)

Add to dashboard:
![image](https://user-images.githubusercontent.com/60582161/209435728-96989809-d80d-4d46-8275-09d578f84b18.png)

**Comment by sfstar** [comment]
Hello and thank you for opening this issue.
I'm not sure why the unique id is not being set for you.
In my own production setup (running the latest released version) every entity (including my grid energy forward total entity) has a unique id.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/6717280/210131187-72a3e720-42f2-4246-9f85-5e19b1abd846.png">

Is the unique id not being set (at your end) occuring for every entity provided by this integration?

**Comment by OlePZ9** [comment]
I reinstalled the integration and now it works from this point. This time the IP Address (without http:// before) gave me success. But now, I have another Issue. Will open a new one and close this one, thanks!
