### ISSUE TITLE
missing Victron Solarcharger after change Charger hardware

### ISSUE THREAD

**Issue by Heiko00000** [sfstar/hass-victron#179]
Hello,

I build a HA System with RP5 and actuell software Januar 2024. 
Yesterday, i musst change  the MPPT 150/60 (faulty) against the same type.

In Victron VRM is the Charger find and work normaly.

The Rescan find no Solarcharger.
Delate the Victron Hub in HA and Scan, 5 Items find, no Solarcharger.

New Apdate  for Victron Cerbo GX von 3.13 to 3.22, no improvement.
New Apdate HA to Home Assistant (2024.2.3) to 2024.2.5. no improvement.
New apdate hass-victron to V0.1.7, no improvement.

Solarcharger have the Number 216 /281

Thanks Heiko

**Comment by Heiko00000** [comment]
Hello,

I did a test, reconnected the defective solar charger to the Cerbo and after another scan HA found it. HA model number 224, Victron ID 278.
Reconnected the new solar charger, HA cannot find a charger.
Disabled the defective and disconnected solar charger in HA, no improvement.
![Screenshot 2024-03-07 091624](https://github.com/sfstar/hass-victron/assets/157812885/bba6d36b-08dd-462c-9579-5a58950d6df1)

Does anyone have an idea where the error is?

Thank you, Heiko

**Comment by Heiko00000** [comment]
Hello und thanks for your help.

The Solarcharge have the VRM Instance 281.
In Hass-Victron it should be 216.

Heiko

**Comment by sfstar** [comment]
Hello @Heiko00000,

Is either 281 or 216 the id that is visible on this screen:
<img width="525" alt="image" src="https://github.com/sfstar/hass-victron/assets/6717280/8e30df00-4dd2-41f8-8ca6-c28eec1f9b6d">
related to the victron solarcharger?

**Comment by sfstar** [comment]
You can try installing the latest main version by:
Going to hacs
Selecting redownload for the integration.
There you select "main" as the version (since the unit id change hasn't been released yet).

After downloading, restart HA and perform a rescan of all available devices.
This should then yield the new solarcharger as an device.

**Comment by Heiko00000** [comment]
Hello, 
the solarcharger is found and works, thank you.  

But I had to enter the number 216 directly in the "const.py" because the call "main" kept getting replaced by 0.1.7.  

Greetings Heiko

**Comment by sfstar** [comment]
The release has been shipped.
Closing issue, feel free to re-open if the issue persists with the new release
