### ISSUE TITLE
No more than 1 PV-inverter?

### ISSUE THREAD

**Issue by AminShAT** [sfstar/hass-victron#182]
Hi, I am using a couple of decentralized Hoymiles invertes additionally to my Victron MPPT loader. They are all nicely integrated into Victron via the openDTU.

The integration manages to find the find first one, but only one. The others don't show up as devices.

**Comment by sfstar** [comment]
Hello @AminShAT,

Most likely the unit ID of your other pv inverters isn't being scanned by the 0.1.7 release.
The main branch contains code that will most likely cause your pv inverters to be detected correctly.
You can install this via going to:
- HACS 
- Selecting the hass-victron integration
- Selecting the hamburger menu in the top right.
- Selecting redownload
<img width="295" alt="image" src="https://github.com/sfstar/hass-victron/assets/6717280/0a10a4f2-6325-41cb-93eb-7f8a125b951e">

- Clicking the drop down and selecting main as the version
- Clicking download

<img width="613" alt="image" src="https://github.com/sfstar/hass-victron/assets/6717280/94a35342-66f2-4930-b0e1-9813c1688eef">

- Restarting HA
- Rescanning all available devices

Please let me know if after installing the main version your other PV inverters are being correctly detected

**Comment by AminShAT** [comment]
Hello, thanks for your detailed instructions. I followed them, but to no avail so far.

Here are a few screenshots:

Installed version of the Victron integration

![image](https://github.com/sfstar/hass-victron/assets/133445212/375f4865-5860-43d4-a947-d88e826842f5)

Found devices

![image](https://github.com/sfstar/hass-victron/assets/133445212/f5d51518-771d-41b7-aec8-06f652bc1944)

List of openDTU inverters registered in the Cerbo

![image](https://github.com/sfstar/hass-victron/assets/133445212/2be98060-4f53-4826-9994-167323732012)

**Comment by sfstar** [comment]
That would also be helpfull as a future test.
Please see https://github.com/victronenergy/dbus_modbustcp/blob/master/CCGX-Modbus-TCP-register-list.xlsx for a list of unit id's that victron is supposed to expose.

Just to confirm, have you managed to get the pvinverter detected with the latest main version?
Since there are also other users (with for example issue #137) that report unit's with id 35 and 36 not being found.
If you are able to get it detected with id 35 in the latest main version it would allow me to create an release that would solve unit detection issues for a lot of people.

**Comment by AminShAT** [comment]
Unfortunately not. I tried both. Switching to 101-103 and leaving at 34-36. in both cases, it shows only the one at 34. even when switching to 101-103 it does not find anything new and still claims to have only one at 34.

**Comment by sfstar** [comment]
Could you perhaps send me another screenshot of the installed commit with which you performed the test?
And just to confirm the manual triggered rescan only resulted in 34 being found as a device?

**Comment by AminShAT** [comment]
Apologies, I was too quick in clicking. Seems, you need to wait until the right version is really selected before installing.

I tried now with 34-36 and all inverters are found.

![image](https://github.com/sfstar/hass-victron/assets/133445212/8e511b97-c1fb-4a29-8120-89b3157b84ea)

**Comment by sfstar** [comment]
No worries, I've made the same mistake in the past :).
Thanks for testing and your quick replies.

Great to hear that units 35 and 36 are now discovered by the integration.
This means that in the next release a lot of unit id related issues are going to be closeable. #8 #36 #137 and possibly #129, #157, #179.

**Comment by sfstar** [comment]
The release (v0.2.0) has been shipped.
Closing issue, feel free to re-open if the issue persists with the new release

**Comment by AminShAT** [comment]
I got a forth microinverter meanwhile. It is at ID 37, but is not found by the integration. I think you only included up to 36.

Is it possible to add the numbers above as well? I will get even 2 more microinverters, so a total of 6 (range 34 - 39).

Thanks in advance

Amin

**Comment by sfstar** [comment]
Hello Amin,

Please open a new issue so that this can be tracked seperately.
