### ISSUE TITLE
Vebus decode errors

### ISSUE THREAD

**Issue by Off-Grid-Garage** [sfstar/hass-victron#189]
Some vebus error popping up in the log files now:

![313458771-42387a9e-ed8a-47d2-a069-ed91a9a1ae19](https://github.com/sfstar/hass-victron/assets/113171448/70f574d6-375d-40ce-85b1-4b9f27b853d1)

![313458793-89a08fed-f3a7-44df-a311-a6a194a07a19](https://github.com/sfstar/hass-victron/assets/113171448/4f9606fb-8c5c-4a9a-be2f-42a973382a66)

![image](https://github.com/sfstar/hass-victron/assets/113171448/0083c449-e6fb-4dc3-84fa-e39aec07eb7e)

![image](https://github.com/sfstar/hass-victron/assets/113171448/000e2859-203b-4845-9c76-bd11091f018c)

**Comment by Off-Grid-Garage** [comment]
Seems to be working great. Since I restarted HA, no more Victron related errors or warnings in the log...

**Comment by sfstar** [comment]
The release (v0.2.0) has been shipped.
Closing issue, feel free to re-open if the issue persists with the new release
