### ISSUE TITLE
Two batteries - Integration only one showing

### ISSUE THREAD

**Issue by Levanterman** [sfstar/hass-victron#217]
Hi

Great integration, love it, but slight problem, with the integration 
I have two batteries , and although the SoC and Soc2 are showing, they are identical, you can see the screen shots of the Cerbo showing two batteries, but this integration showing two identical readings in the integration.

I have 2 x settings showing in the integration, but one battery,  the settings and battery components show the same % of one of the battery, no sign of the other battery.

<img width="809" alt="vic4" src="https://github.com/sfstar/hass-victron/assets/49679006/403acdb7-29cd-4869-8c02-332e96ec3b56">

Thanks

<img width="349" alt="vic5" src="https://github.com/sfstar/hass-victron/assets/49679006/0cd23d86-a553-49a6-a200-7fd14eca5a2d">

<img width="496" alt="vic6" src="https://github.com/sfstar/hass-victron/assets/49679006/052613f6-2074-47f9-821e-a54b37aca1c6">

<img width="569" alt="vic1" src="https://github.com/sfstar/hass-victron/assets/49679006/acc279d2-1e9f-4ada-910c-83668649ead0">

**Comment by sfstar** [comment]
Thank you for opening this issue.
Could you perhaps share the unit id's of the batteries that are connected in your system?
You can find them under:
"Settings -> services -> Modbus TCP -> available services"

**Comment by Levanterman** [comment]
> Thank you for opening this issue. Could you perhaps share the unit id's of the batteries that are connected in your system? You can find them under: "Settings -> services -> Modbus TCP -> available services"

Thanks for the reply, I went to Available Services and now I can see why the second battery is not showing.
![image](https://github.com/sfstar/hass-victron/assets/49679006/93009b6a-e4c8-47ca-b605-f4885b16ae2b)

only 1 battery is being publlished by Modbus, and then i remembered that when you add the second battery to the system you do not connect the second battery to the BMS-CAN, here is a snippet from the Drift Pro Manual:

![image](https://github.com/sfstar/hass-victron/assets/49679006/7e0ed3d7-17c0-4150-bb8f-c24912900ef7)

So both batteries show up in the Cerbo but one is connected to the BMS-CAN and the other to VE-CAN

![image](https://github.com/sfstar/hass-victron/assets/49679006/97cc0850-1dce-416d-898d-7c46ce239bf6)

So as well as Modbus I enabled MQTT, and I can see the other battery on the Cerbo MQTT
![image](https://github.com/sfstar/hass-victron/assets/49679006/91aaca8e-3f34-48e4-bd47-0a8c4208258a)

so i added entities in the configuration.yaml from the MQTT and used those entities for the second battery, Soc, Volt, Current and you can see in the graphical integration

![image](https://github.com/sfstar/hass-victron/assets/49679006/5273a101-cb50-423e-8efd-8d084646adc6)

Looks like the instanceID might be 512, but its not being published by Modbus so maybe not accessible by your integration, but thank you , it great.
