### ISSUE TITLE
settings ess max dischargepower

### ISSUE THREAD

**Issue by Alexander1714** [sfstar/hass-victron#237]
There is obviously a max limit of 1700 Watt which i can not explain.
![settings_ess_maxdischargepower](https://github.com/user-attachments/assets/1b984aa6-b167-4f6c-b46b-2c62319babd1)
Venus OS show this 1700 Watt. But in Venus OS it is possible to set up to 3500Watt.
HA core is 2024.9.3 OS: 13.1
hass-victron: 0.0.11

**Comment by dougle03** [comment]
I'm having the same problem. Have you tried removing the integration and re-adding it? I think it takes the min/max from the Cerbo at time of setup and does not update when you make changes using VEConfig.

**Comment by Alexander1714** [comment]
Hi Peter, no i didn`t try to remove the integration. I´m a little bit scared of it. I don´t think there was a min/max during the installation of the venus os. It doesn´t matter which limit is set for maxdischargepower. It is always 1700W in the venus os.

**Comment by Alexander1714** [comment]
I changed the language from German to English, then the limit of the inverter power shows again1700 W. So Peter, you are maybe wright. This strange powerlimit of 1700 W is a setting in the venus os. Do you have any idea how to change this setting?

**Comment by dougle03** [comment]
Turns out that it's related to the configuration in HA when adding the integration. You can change it by going back to the HA integration, pay attention to the Amps entry.
![image](https://github.com/user-attachments/assets/1eee8da2-fca7-442d-b0f2-a349d36f1438)

**Comment by Alexander1714** [comment]
OMG, i´am an idiot. Thank you so much for your help Peter. It works perfect now.

**Comment by Alexander1714** [comment]
I had a wrong **DC current limit setting** in HA. I´ve change it from 35 to 55 A wich is now close to 2600 W for  the inverter.

**Comment by dougle03** [comment]
No worries, I had the same problem.
