### ISSUE TITLE
GPS Altitude Wrong Unit of measure

### ISSUE THREAD

**Issue by Next9999** [sfstar/hass-victron#28]
GPS Altitude Wrong Unit of measure

m/s should be meter only

![image](https://user-images.githubusercontent.com/54117519/213949960-b50f8bfc-12f8-41b1-92f6-f734d9fd567a.png)

**Comment by flyrmyr** [comment]
I've noticed the same with my manual setup in the past. The Cerbo is actually passing that as the unit value... Seems the error might be with VenusOS. Also, my value is just wildly off. Head scratcher.

**Comment by sfstar** [comment]
Thank you for reporting.
It indeed is an incorrect defintion in the modbus specification sheet
<img width="1791" alt="Screenshot 2023-02-03 at 20 26 34" src="https://user-images.githubusercontent.com/6717280/216690481-a60220cf-e4c8-4e8d-8ec6-0175c6d865a3.png">
Please see my comment in #36 as to why fixing this in the integration is currently on hold

**Comment by askpatrickw** [comment]
Looks like Victron isn't engaging on the open issue, How about we test a fix?

Is the fix to change `"gps_altitude": RegisterInfo(2808, INT32, UnitOfSpeed.METERS_PER_SECOND, 10)` to "gps_altitude": RegisterInfo(2808, INT32, UnitOfSpeed.METERS, 10)

https://github.com/sfstar/hass-victron/blob/3b7fd201de6d7bc2daac1fd51b51ec46990660e3/custom_components/victron/const.py#L618C81-L618C81

**Comment by askpatrickw** [comment]
BTW, the attributes.csv in the Victron repo says meters "m" now.

https://github.com/victronenergy/dbus_modbustcp/blob/master/attributes.csv#L7
`com.victronenergy.gps,/Altitude,d,m,2808,int32,10,R`

**Comment by askpatrickw** [comment]
https://github.com/victronenergy/dbus_modbustcp/issues/31 is now closed and they mention they will update the docs accordingly.

**Comment by sfstar** [comment]
Closing issue as fixed
