### ISSUE TITLE
HA version 2022.2.0 with hass-victron v0.0.7

### ISSUE THREAD

**Issue by flyrmyr** [sfstar/hass-victron#39]
Just updated my HA core instance to the one released today. I didn't receive a HACS update option for this Victron integration, and on `redownload` I'm seeing this.

<img width="580" alt="Screenshot 2023-02-01 at 3 30 31 PM" src="https://user-images.githubusercontent.com/14035884/216179176-055cb705-8ab2-41c0-9dab-c9be0a6babd1.png">

Attempting to continue anyway just hangs on the updating spinner.

**Comment by sfstar** [comment]
Thank you for reporting. 
This was a typo in the hacs.json file. 
It should now be resolved. 
However, hacs might take a reboot or some time for this to reflect in the available updates

**Comment by sfstar** [comment]
I've currently installed v0.0.7 on two systems after my previous comment.
Therefore I'm closing this issue as resolved.
Feel free to re-open if you're still experiencing this issue on your end
