### ISSUE TITLE
Missing 1-wire sensor

### ISSUE THREAD

**Issue by mapeje** [sfstar/hass-victron#45]
I am using RpiGpioSetup and have a DS18B20 OneWire temperature sensor connected. It shows up in VRM as  "VRM instance 101" but it does come through to Home Assisstant. I only see my Ruuvi temperature sensor, VRM instance 20.

**Comment by sfstar** [comment]
Thank you for reporting this issue.
Does the DC18B20 also show up in the "available services" section for the modbus service on the GX device?

**Comment by mapeje** [comment]
Yes, it shows Unit ID 101, see below. For the HA integration, I only get "1", "20", "100"
<img width="486" alt="image" src="https://user-images.githubusercontent.com/52676832/216779552-c2087ecc-abe1-4d69-b8c8-2bcea78ca396.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/52676832/216779580-3a1ec573-a297-4612-9b6b-67c7664b4879.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/52676832/216779616-5e63753b-bff9-46e8-95a8-bdbc3e55d148.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/52676832/216779642-a5ea3102-226c-4359-aee6-6b4af33faffb.png">

**Comment by sfstar** [comment]
Hello @mapeje,

Sorry for the long wait between your report and your issue being picked up.
The change that should allow your 1-wire sensor to be detected by the integration is now pushed to main.
Please install the main version of the integration and check if the device is detected correctly after a rescan.

**Comment by sfstar** [comment]
The issue has been shipped in the latest release (v0.3.0) closing issue as resolved.
Feel free to re-open if the issue persists with the v0.3.0 release
