### ISSUE TITLE
changing number.victron_settings_ess_maxdischargepower error: required argument is not an integer

### ISSUE THREAD

**Issue by ChristophPech** [sfstar/hass-victron#48]
When changing the number.victron_settings_ess_maxdischargepower slider in the UI, I get an error message that the required argument is not an integer because it's a floating point number.

**Comment by cm2962** [comment]
I observe the same. 
![image](https://user-images.githubusercontent.com/75210597/217757694-d466c52d-f94a-4336-a603-3807753c2437.png)

**Comment by andzie82** [comment]
Hi, is this related to my issue as well? #52

**Comment by ChristophPech** [comment]
Not really. I added configurable steps size in the code, but you need configurable range in the UI. Most people don't want to have a range larger than necessary because then the UI becomes difficult to use, outright impossible on mobile even.

**Comment by andzie82** [comment]
I don’t know if I did something wrong when setting it up but I first put in 20A but I changed it to 60A instead. I guess it doesn’t take in effect if you have a 3 phase system or not.

**Comment by sfstar** [comment]
This issue should now be adressed in the latest release containing the fix made by @ChristophPech.
I will close this issue if there are no further reports in the coming weeks
