### ISSUE TITLE
Ruuvi Sensors Not Updating

### ISSUE THREAD

**Issue by rv10guy** [sfstar/hass-victron#60]
I am not sure if this is the same problem as Issue #46 but my Ruuvi temp sensors do not update. They do update correctly when HA restarts but then they just hold at their initial value. I have checked VRM and they do update there. I am using a Cerbo.

**Comment by sfstar** [comment]
Hello and thank you for opening this issue,

Since #46 was resolved last year I'm guessing your issues have also been resolved as well.
Therefore, I'm closing your issue as complete (This will help me cleanup stale issues).
Please feel free to re-open if the issue persists.
