### ISSUE TITLE
 (<class 'custom_components.victron.sensor.VictronSensor'>) is using state class 'measurement'

### ISSUE THREAD

**Issue by Next9999** [sfstar/hass-victron#62]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:497
Integration: Sensor (documentation, issues)
First occurred: 08:16:39 (4 occurrences)
Last logged: 08:16:39

Entity sensor.victron_tank_capacity_20 (<class 'custom_components.victron.sensor.VictronSensor'>) is using state class 'measurement' which is impossible considering device class ('volume') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_tank_remaining_20 (<class 'custom_components.victron.sensor.VictronSensor'>) is using state class 'measurement' which is impossible considering device class ('volume') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_tank_capacity_21 (<class 'custom_components.victron.sensor.VictronSensor'>) is using state class 'measurement' which is impossible considering device class ('volume') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_tank_remaining_21 (<class 'custom_components.victron.sensor.VictronSensor'>) is using state class 'measurement' which is impossible considering device class ('volume') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by sfstar** [comment]
Hello and thank you for opening this issue.
Could you install the main branch version of this integration (via hacs with beta versions enabled) and check whether the error persists.

**Comment by sfstar** [comment]
Closing issue as resolved with release v0.0.10.
Feel free to re-open is the issue persists in your setup
