### ISSUE TITLE
Set currentlimit for mppt: -> Value 40.0 for number.victron_vebus_activein_currentlimit_235 is outside valid range -32 - 32

### ISSUE THREAD

**Issue by pos-ei-don** [sfstar/hass-victron#66]
I have an MPPT250/60.

Setting currentlimit does generally not work. When I try to set a value, nothing happens.
When i try to send an value >32, i get this errormessage.
But setting  up to 60 should be possible.

**Comment by sfstar** [comment]
@pos-ei-don could you comment the entity_id of the number you are trying to change?

**Comment by pos-ei-don** [comment]
I am currently out of coubtry. I will test it when I come back home.

**Comment by sfstar** [comment]
Closing stale issue, please re-open if the issue still persists
