### ISSUE TITLE
number.victron_vebus_l1_acpowersetpoint_239 can only be changed in steps of 100

### ISSUE THREAD

**Issue by mroggi** [sfstar/hass-victron#73]
Is this a feature or can I control the Victron Multiplus in more granular way?

**Comment by sfstar** [comment]
You can set any value you want via automations or service calls. 
For simplicity the sliders use a 100watt step range.
An enhancement request that might also address your request is: #57

**Comment by sfstar** [comment]
@mroggi does the latest release address your feature request?

**Comment by mroggi** [comment]
Yes, thank you!

**Comment by sfstar** [comment]
Closing as complete
