### ISSUE TITLE
various numeric settings became unavailable since update to HA 2023.5.3

### ISSUE THREAD

**Issue by 1984ozone1984** [sfstar/hass-victron#76]
Since update to HA version 2023.5.3 nearly all numeric settings became unavailable. Sensors are all working fine.

Thanks a lot for your help!
Stefan

<img width="447" alt="Bildschirmfoto 2023-05-17 um 20 09 57" src="https://github.com/sfstar/hass-victron/assets/114089236/ae78bf2c-a5cd-42f1-914f-cb39b5504a20">
<br>

<img width="304" alt="Bildschirmfoto 2023-05-17 um 20 05 52" src="https://github.com/sfstar/hass-victron/assets/114089236/53d322fd-6077-46b3-95a2-c8ec10fda5bc">

**Comment by sfstar** [comment]
Hello and thank you for opening this issue.
Have you also updated the integration recently.
If so please remove the integration (as instructed in the release notes) and configure the integration again.
The entities should come back with the same id's and no automations etc should be affected by this action.

If the issue persists after removing and configuring the integration then please let me know

**Comment by 1984ozone1984** [comment]
Hi,
thanks for your answer. Indeed the removal and reconfiguration of the integration solved the issue.
Sorry for the inconvenience of not fully reading the release notes!
