### ISSUE TITLE
wrong/inappropriate device_class assignment for sensor.victron_settings_ess_batterylife_soclimit

### ISSUE THREAD

**Issue by randyoo** [sfstar/hass-victron#85]
sensor.victron_settings_ess_batterylife_soclimit is incorrectly assigned the "battery" device class (which HA interprets as representing the battery's SoC):

![Screenshot 2023-06-13 at 11 20 47 AM](https://github.com/sfstar/hass-victron/assets/7457804/0b6731f2-2750-426a-a1b0-7f3922b2a05e)

Unsetting this should result in HA appropriately using sensor.victron_system_battery_soc to show the device's battery status.

**Comment by sfstar** [comment]
Issue has been addressed since v0.2.0, issue tracking change #130
