### ISSUE TITLE
Battery sensors for charge and discharge

### ISSUE THREAD

**Issue by AminShAT** [sfstar/hass-victron#89]
Hi, I can't get the Integration working to provide sensors for the HASS default energy dashboard

**Comment by mmaritz** [comment]
I have the same issue and need these to get the energy dashboard in HA working!
![image](https://github.com/sfstar/hass-victron/assets/16016404/1b1c8a75-b2ab-4a4a-80f7-87a23bd12576)

**Comment by sfstar** [comment]
If you are using a battery that is connected via can than these registers do not populate.
If your battery is not connected via can you could try to manually read the register to see whether the modbus server populates the register with any data.

**Comment by mmaritz** [comment]
Victron VE.CAN is pretty standard - why don't they populate?  Victron issue or this Integration?

**Comment by sfstar** [comment]
<img width="1679" alt="image" src="https://github.com/sfstar/hass-victron/assets/6717280/03c7bf4a-8e79-40fc-a0b4-c992d2ef2c40">
I can't populate what isn't provided
