### ISSUE TITLE
L3 usage not shown correctly

### ISSUE THREAD

**Issue by AminShAT** [sfstar/hass-victron#92]
Hi, I compared the usages shown in HA with the ones in VRM and on the Cerbo and for me, L3 is missing about 600W in the sensor sensor.victron_vebus_out_l3_power_227

Where Cerbo and VRM are showing 2.100 Watt, HA is only showing 1.500 Watt right now.

**Comment by pos-ei-don** [comment]
I checked. Cannot see this here.

**Comment by AminShAT** [comment]
It seems to be different values, but right now, I again see a difference between VRM and HA:Am 28.06.2023 um 10:34 schrieb pos-ei-don ***@***.***>:﻿
I checked. Cannot see this here.

**Comment by AminShAT** [comment]
Consumptions are still not correct and do not sum up to battery in/out and grid in HA. Victron VRM shows different consumption s well.

**Comment by sfstar** [comment]
Hello AminShAT,

Perhaps there is an difference between the polling of the integration and perhaps vrm averaging consumption over a larger period of time.
Is the load consistant during the entire period and is the delta exactly the same during the period in question?

**Comment by AminShAT** [comment]
I found the reason:

The consumption parameters do not take into account AC PV production. As I had so far all of my microinvertes on L3, it only affected L3.

In order to calculate the real consumption one needs to substract system.pvoutput (at least in my case).

Issue can be closed.

**Comment by sfstar** [comment]
Thank you for reporting back.
Closing this issue as informed by reporter.
