### ISSUE TITLE
VECan Device is not availabe after HA restart

### ISSUE THREAD

**Issue by dersch81** [sfstar/hass-victron#96]
Using v 0.1.2

After a HA restart all the victron devices are up. But one VEcan device (the only one in the system) is unavailable. I need to manually reconfigure => rescan devices to get it back available in HA.

**Comment by dummy74** [comment]
I have the same problem. After restarting HA I always have to reconfigure the victron integration and set the rescan option. 
This problem has existed since the beginning.

**Comment by sfstar** [comment]
Thank you for opening this issue.
Does the vecan modbus id change between reboots?
What does the logging say, which versions are you running (gx device, this integration, ha)

**Comment by dersch81** [comment]
Hi no, the vecan modbus id ist always 0 

I'm running Venus 3.0, Integration 0.1.2 and HA 2023.6.3

**Comment by cm2962** [comment]
same here

**Comment by ppbering** [comment]
Hello,
I have the same issu on my system, every time HA restart (for any update the system as to deal with), I MUST rescan available devices to be able to retrieve values from one of my solar array.
And I have not been able ton understand what is happenning.
I only loose one device, but it's making a huge mess in all my automations and the energy dashboard.

Thanks for your time on this matter.

Regards

**Comment by dersch81** [comment]
is there no way to just rescan automatically after restart of HA?

**Comment by viccooper142** [comment]
Same issue. Is there a file we can edit to make rescan happen after every restart? Or make it so the check box under configuration stays checked?

**Comment by sfstar** [comment]
The issue has been shipped in the latest release (v0.3.0) closing issue as resolved.
Feel free to re-open if the issue persists with the v0.3.0 release
